### ISSUE TITLE
Validation errors on resource pools

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-data-services#57]
From the logs on renkulab.io

```
[2023-09-19 10:02:42 +0000] [21] [ERROR] An unknown or unhandled exception occurred
Traceback (most recent call last):
  File "/app/env/lib/python3.11/site-packages/sanic_ext/extras/validation/validators.py", line 25, in validate_body
    return validator(model, body)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/env/lib/python3.11/site-packages/sanic_ext/extras/validation/validators.py", line 35, in _validate_instance
    return model(**data)
           ^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ResourcePool
name
  ensure this value has at least 5 characters (type=value_error.any_str.min_length; limit_value=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/app/env/lib/python3.11/site-packages/renku_crc/auth.py", line 23, in decorated_function
    response = await f(request, *args, **kwargs, user=user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/env/lib/python3.11/site-packages/renku_crc/auth.py", line 42, in decorated_function
    response = await f(request, *args, **kwargs, user=user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/env/lib/python3.11/site-packages/sanic_ext/extras/validation/decorator.py", line 40, in decorated_function
    await do_validation(
  File "/app/env/lib/python3.11/site-packages/sanic_ext/extras/validation/setup.py", line 35, in do_validation
    validation = validate_body(validator, model, data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/env/lib/python3.11/site-packages/sanic_ext/extras/validation/validators.py", line 27, in validate_body
    raise ValidationError(
sanic_ext.exceptions.ValidationError: Invalid request body: ResourcePool. Error: 1 validation error for ResourcePool
name
  ensure this value has at least 5 characters (type=value_error.any_str.min_length; limit_value=5)
```

**Comment by m-alisafaee** [comment]
This is expected since we require resource pool names to be at least 5 characters: https://github.com/SwissDataScienceCenter/renku-data-services/blob/449e1b7a530254f658d0bcdf3c24ea65c9845a28/components/renku_data_services/crc/api.spec.yaml#L1380 We can change it to 1 if required.
